os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - 'lts/*'
services:
  - xvfb
install:
  - npm set progress=false
  - npm install
script:
  - npm run lint
  - npm run build
  - npm run test
